<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxt8tni\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxt8tni/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTxt8tni.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTxt8tni\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTxt8tni\appProdProjectContainer([
    'container.build_hash' => 'Txt8tni',
    'container.build_id' => 'b81c5bff',
    'container.build_time' => 1577113764,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxt8tni');
